controllers/DataController.php
<?php

namespace app\controllers;

use app\models\CsvData;
use app\models\CsvDataSearch;
use app\models\Logs;
use app\models\SubData;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * DataController implements the CRUD actions for CsvData model.
 */
class DataController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CsvData models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CsvDataSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CsvData model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CsvData model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CsvData();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing CsvData model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing CsvData model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CsvData model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CsvData the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CsvData::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * @param $id
     */
    public function actionLogs($id)
    {
        if (Yii::$app->request->isAjax) {

            $searchModel = new CsvDataSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->renderAjax('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * @return string
     */
    public function actionMergeDuplicates()
    {
        if (\Yii::$app->session->get('duplicates')) {

            $message = \Yii::$app->session->getFlash('duplicate_msg');
            $data = \Yii::$app->session->get('duplicates');

            return $this->render('duplicates', [
                'model' => $data,
                'message' => $message
            ]);
        }
    }


    /**
     * @return string
     */
    public function actionSaveDuplicates()
    {
        if (Yii::$app->request->post()) {

            $data = \Yii::$app->session->get('duplicates');

            $array = [];
            $errors = [];

            if (count($data) > 0) {

                foreach ($data as $record) {

                    $model = new SubData();
                    $array['SubData'] = $record;

                    $model->load($array);
                    if (!$model->save()) {
                        $errors[] = $model->getErrors();
                    }
                }

                if (count($errors) > 0) {
                    Yii::$app->session->setFlash('errors', $errors);
                } else {
                    Yii::$app->session->setFlash('success', "Record Merged");
                }

                \Yii::$app->session->set('duplicates', null);
                $this->redirect(['/data']);

            }

        } else {

            \Yii::$app->session->setFlash('duplicate_msg', 'Some Message!');
            $this->redirect(['/data']);

        }
    }

    /**
     * @param $id
     * @param string $type
     * @return string
     */
    public function actionSaveLogs($id, $type = "main")
    {
        $model = new Logs();
        $model->data_id = $id;
        $model->type = $type;

        $chats = Logs::find()->where(['data_id' => $id])
            ->andWhere(['type' => $type])
            ->orderBy([
                'id' => SORT_DESC
            ])->all();

        return $this->renderAjax('_logs', [
            'model' => $model,
            'logs' => $chats,
            'id' => $id,
            'type' => $type
        ]);

    }


    public function actionSubmitLogs($id, $type = "main")
    {
        $model = new Logs();
        $model->data_id = $id;
        $model->type = $type;

        if (Yii::$app->request->post()) {

            $model->load(Yii::$app->request->post());

            if ($model->save()) {

                if ($type == "main") {
                    $main_data = CsvData::find()->where(['id' => $id])->one();
                } else {
                    $main_data = SubData::find()->where(['id' => $id])->one();
                }

                $main_data->isNew = 0;
                $main_data->interests = $model->interests;
                $main_data->save();

                Yii::$app->session->setFlash('success', 'Logs saved');
            } else {
                Yii::$app->session->setFlash('error', 'Log not saved');
            }

        }

        $chats = Logs::find()->where(['data_id' => $id])
            ->andWhere(['type' => $type])
            ->orderBy([
                'id' => SORT_DESC
            ])->all();

        $html = "";
        if ($chats <> null) {
            foreach ($chats as $chat) {

                $agenda = "";
                $date_time = "";
                $venue = "";

                if ($chat->agenda) {
                    $agenda = '<strong>Agenda: </strong>' . $chat->agenda . '<br/>';
                }

                if ($chat->date_time && $chat->date_time != "0000-00-00 00:00:00") {
                    $date_time = '<strong>Time: </strong>' . $chat->date_time . '<br/>';
                }

                if ($chat->venue) {
                    $venue = '<strong>Venue: </strong>' . $chat->venue . '<br/>';
                }


                $html .= '<div class="box-comment">
                            <div class="comment-text">
                                    <span class="username">
                                         <i class="fa fa-comment"></i>&nbsp;' . $chat->comments . '<br/>
                                        <span class="text-muted pull-right">
                                            ' . date("D M j G:i:s", strtotime($chat->date_comment)) . '
                                        </span>
                                    </span><br/>
                                    <p>' . $agenda . $date_time . $venue . '</p>
                            </div>
                            <!-- /.comment-text -->
                        </div>';


            }
        }

        echo $html;
        return;
    }

    /**
     *
     */
    public function actionUpdateStatus()
    {

        if (Yii::$app->request->post()) {

            $type = Yii::$app->request->post('type');

            if ($type == "main") {

                $model = CsvData::findOne(Yii::$app->request->post('id'));
                $model->status = Yii::$app->request->post('status');

                if (!$model->save()) {

                    echo 0;
                    return;
                }

                echo 1;
                return;
            }

            if ($type == "sub") {

                $model = SubData::findOne(Yii::$app->request->post('id'));
                $model->status = Yii::$app->request->post('status');

                if (!$model->save()) {

                    echo 0;
                    return;
                }

                echo 1;
                return;
            }

        }
    }

    /**
     *
     */
    public function actionUpdateSource()
    {

        if (Yii::$app->request->post()) {

            $model = CsvData::findOne(Yii::$app->request->post('id'));
            $model->source = Yii::$app->request->post('source');

            if (!$model->save()) {

                echo 0;
                return;
            }

            echo 1;
            return;

        }
    }

    /**
     *
     */
    public function actionUpdateSourceSub()
    {

        if (Yii::$app->request->post()) {

            $model = SubData::findOne(Yii::$app->request->post('id'));
            $model->source = Yii::$app->request->post('source');

            if (!$model->save()) {

                echo 0;
                return;
            }

            echo 1;
            return;

        }
    }

views/data/_change_source.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CsvData */
/* @var $form yii\widgets\ActiveForm */
?>
<!---->

<div class="csv-data-form">
    <div class="row">

        <div class="col-md-12">
            <?php
            echo Html::dropDownList('source',
                $model->source,
                ArrayHelper::map(\app\models\Sources::find()->all(), 'id', 'title'), [
                    'id' => $model->id,
                    'class' => 'change_source sub_change_source form-control',
                    'prompt' => 'Select ...'
                ]);
            ?>
        </div>
        <div class="col-md-12">
            <div class="label label-success change_source_label hidden" id="success">Source changed!</div>
            <div class="label label-success change_source_label hidden" id="error">Error! Source could not be changed!
            </div>
        </div>
        <div class="col-md-12"  style="position: absolute;bottom: 25px;text-align: right;right: 10px;">
            <span class="button btn btn-primary" data-dismiss="modal" aria-label="Close">close</span>
        </div>
    </div>
</div>

views/data/_change_status.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CsvData */
/* @var $form yii\widgets\ActiveForm */
?>
<!---->

<div class="csv-data-form">
    <div class="row">

        <div class="col-md-12">
            <?php
            echo Html::dropDownList('source',
                $model->source,
                ArrayHelper::map(\app\models\Status::find()->all(), 'id', 'title'), [
                    'id' => $model->id,
                    'class' => 'change_status form-control',
                    'prompt' => 'Select ...'
                ]);
            ?>
        </div>
        <div class="col-md-12">
            <div class="label label-success change_source_label hidden" id="success">Source changed!</div>
            <div class="label label-success change_source_label hidden" id="error">Error! Source could not be changed!
            </div>
        </div>
        <div class="col-md-12"  style="position: absolute;bottom: 25px;text-align: right;right: 10px;">
            <span class="button btn btn-primary" data-dismiss="modal" aria-label="Close">close</span>
        </div>
    </div>
</div>

views/data/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CsvData */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="csv-data-form background_card">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone_number')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'domain')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'compnay')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <?= $form->field($model, 'registration_date')->textInput() ?>

    <?= $form->field($model, 'expiry_date')->textInput() ?>

    <?= $form->field($model, 'server')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ip_address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'country')->textInput() ?>

    <?= $form->field($model, 'category')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/data/duplicates.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Merge Duplicates';
?>
<div class="site-index">
    <div class="jumbotron">
        <h4>Attention!</h4>
        <p class="lead">
            You have <?= count(\Yii::$app->session->get('duplicates'));?> duplicate records in the list. Do you wish to merge this?
        </p>
        
        <p>
            <?= Html::a('Yes! Merge', Url::to(['/data/save-duplicates']), ['data-method' => 'POST', 'class' => 'btn btn-lg btn-success']) ?>
            <a class="btn btn-lg btn-warning" href="/data">No! go to listing</a>
        </p>
    </div>
    <div class="body-content"><div class="row"></div></div>
</div>

views/data/index.php
<?php

use app\models\Sources;
use app\models\Status;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CsvDataSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Data List';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="csv-data-index background_card">

        <p><?= Html::a('Create Csv Data', ['create'], ['class' => 'pull-right btn btn-success']) ?></p>

        <h1><?= Html::encode($this->title) ?></h1>

        <?php echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= GridView::widget([

            'dataProvider' => $dataProvider,
            'columns' => [

                [
                    'attribute' => 'name',
                    'format' => 'raw',
                    'value' => function ($model) {
                        $new = "";
                        if($model->isNew) {
                            $new = "<span class='label label-warning'>New</span>";
                        }
                        return $model->name .$new;
                    }
                ],
                [
                    'attribute' => 'email',
                    'format' => 'raw',
                    'value' => function ($model) {

                        $duplicates = \app\models\SubData::find()->where(['data_id' => $model->id])->count();
                        $email = Html::a($model->email, '#', ['href' => $model->email]);

                        return $email . "&nbsp;&nbsp;<span class='label label-info'>" . $duplicates . "</span>";
                    }
                ],
                'phone_number',
                'domain',
                'compnay',
                [
                    'attribute' => 'interests',
                    'format' => 'raw',
                    'value' => function ($model) {

                        $interests = explode(',', $model->interests);

                        $html = "";
                        if (count($interests) > 0) {
                            foreach ($interests as $interest) {
                                $html .= "<span class='label label-info'>" . $interest . "</span> ";
                            }
                        }
                        return $html;
                    }
                ],
                [
                    'attribute' => 'source',
                    'format' => 'raw',
                    'value' => function ($model) {

                        $sources = Sources::find()->where(['id' => $model->source])->one();
                        $_source = "";
                        if ($sources <> null) {
                            $_source = $sources->title;
                        }

                        return '<span id="source_' . $model->id . '">' . $_source . '</span>' .
                            Html::a('<i class="fa fa-pencil"></i>', '#', [
                                'class' => 'showModalButton',
                                'value' => Url::to(['/data/change-source', 'id' => $model->id, 'type' => 'main']),
                                'title' => Yii::t('yii', 'Change Source'),
                                'style' => 'padding:5px;'
                            ]);

                    }
                ],
                [
                    'attribute' => 'status',
                    'format' => 'raw',
                    'value' => function ($model) {

                        $status = Status::find()->where(['id' => $model->source])->one();
                        $_status = "";

                        if ($status <> null) {
                            $_status = $status->title;
                        }

                        return '<span id="status_' . $model->id . '">' . $_status . '</span>' .
                            Html::a('<i class="fa fa-pencil"></i>', '#', [
                                'class' => 'showModalButton',
                                'value' => Url::to(['/data/change-status', 'id' => $model->id, 'type' => 'main']),
                                'title' => Yii::t('yii', 'Change Source'),
                                'style' => 'padding:5px;'
                            ]);
                    }
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => 'Actions',
                    'headerOptions' => ['style' => 'color:#337ab7'],
                    'template' => '{view}{update}{delete}{logs}',
                    'buttons' => [
                        'logs' => function ($url, $model) {

                            return Html::a('<span class="label label-info"><span class="glyphicon glyphicon-comment"></span></span>', '#', [
                                'class' => 'showModalButton',
                                'value' => Url::to(['/data/save-logs', 'id' => $model->id, 'type' => 'main']),
                                'title' => Yii::t('yii', 'Logs'),
                                'id' => 'commentLog-' . $model->id
                            ]);

                        },
                    ],

                ],
            ],
        ]); ?>
    </div>


<?= $this->registerJs('
   
    /****************************************************/
    
    $("body").on("click", "#SubmitForms", function(e) {
       
        var formAction = $("#LogsForm").attr("action");
        $.ajax({
           type: "POST",
           url: formAction,
           data: $("#LogsForm").serialize(),
           success: function (data) { 
               $("body").find("#comments_logs_container").html(data);
           },
           error: function () {
                alert("Error!!!");
           }
        });
        
        e.preventDefault();
    });
    
    /****************************************************/
    
    $("body").on("click", ".change_status", function(e) {
     
        e.preventDefault(); 
        var data_id = $(this).attr("id"); 
        var status = $(this).val();
        
        $.ajax({
        
            url: "' . Yii::$app->request->baseUrl . '/data/update-status/",
            type: "POST",
            data: { status: status , id : data_id, type : "main" }, 
            success : function(res){
                
                if(res){
                    $("#success").removeClass("hidden");
                    $("#status_"+ data_id).text($(".change_status option:selected").text());
                } else{
                    $("#error").removeClass("hidden");
                }
               
               setTimeout(function(){ 
                    $(".change_source_label").addClass("hidden"); 
                    $("#modal").hide();
               }, 2000);
            },
            error : function(data){
                $("#error").removeClass("hidden");
                setTimeout(function(){ $(".change_source_label").addClass("hidden"); }, 2000);
            }
        }); 
    });
    
    /****************************************************/
    
    $("body").on("click", ".change_source", function(e) {
     
        e.preventDefault(); 
        var data_id = $(this).attr("id"); 
        var source = $(this).val();
        
        $.ajax({
        
            url: "' . Yii::$app->request->baseUrl . '/data/update-source/",
            type: "POST",
            data: { source: source , id : data_id}, 
            success : function(res){
                
                if(res){
                    $("#success").removeClass("hidden");
                    $("#source_"+ data_id).text($(".change_source option:selected").text());
                }else{
                    $("#error").removeClass("hidden");
                }
               
               setTimeout(function(){ 
                    $(".change_source_label").addClass("hidden"); 
                    $("#modal").hide();
               }, 2000);
            },
            error : function(data){
                $("#error").removeClass("hidden");
                setTimeout(function(){ $(".change_source_label").addClass("hidden"); }, 2000);
            }
        });
        
    });
    
    /****************************************************/
    
     
'); ?>

views/data/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use app\models\Sources;
use yii\helpers\Url;
use app\models\Status;
/* @var $this yii\web\View */
/* @var $model app\models\CsvData */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Csv Datas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="csv-data-view background_card">

    <p class="pull-right">
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <div class="card">
        <h1><?= Html::encode($this->title) ?></h1>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'name',
                'email:email',
                'phone_number',
                'domain',
                'compnay',
                'city',
                'date',
                'registration_date',
                'expiry_date',
                'server',
                'ip_address',
                'country',
                'category',
            ],
        ]); ?>
    </div>


    <?= \yii\grid\GridView::widget([
        'dataProvider' => new ActiveDataProvider([
            'query' => $model->getSubData(),
            'pagination' => [
                'pageSize' => 10,
            ]
        ]),
        'columns' => [

            'domain',
            'compnay',
            'city',
            'country',
            [
                'attribute' => 'interests',
                'format' => 'raw',
                'value' => function ($model) {

                    $interests = explode(',', $model->interests);

                    $html = "";
                    if(count($interests) > 0) {
                        foreach ($interests as $interest) {
                            $html .= "<span class='label label-info'>" . $interest . "</span> ";
                        }
                    }
                    return $html;
                }
            ],
            [
                'attribute' => 'source',
                'format' => 'raw',
                'value' => function ($model) {

                    $sources = Sources::find()->where(['id' => $model->source])->one();
                    $_source = "";
                    if ($sources <> null) {
                        $_source = $sources->title;
                    }

                    return '<span id="source_' . $model->id . '">' . $_source . '</span>' .
                        Html::a('<i class="fa fa-pencil"></i>', '#', [
                            'class' => 'showModalButton',
                            'value' => Url::to(['/data/change-source', 'id' => $model->id, 'type' => 'sub']),
                            'title' => Yii::t('yii', 'Change Source'),
                            'style' => 'padding:5px;'
                        ]);

                }
            ],
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($model) {

                    $status = Status::find()->where(['id' => $model->source])->one();
                    $_status = "";

                    if ($status <> null) {
                        $_status = $status->title;
                    }

                    return '<span id="status_' . $model->id . '">' . $_status . '</span>' .
                        Html::a('<i class="fa fa-pencil"></i>', '#', [
                            'class' => 'showModalButton',
                            'value' => Url::to(['/data/change-status', 'id' => $model->id, 'type' => 'main']),
                            'title' => Yii::t('yii', 'Change Source'),
                            'style' => 'padding:5px;'
                        ]);
                }
            ],
            'country',
            'category',
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'headerOptions' => ['style' => 'color:#337ab7'],
                'template' => '{view}{update}{delete}{logs}',
                'buttons' => [
                    'logs' => function ($url, $model) {
                        return Html::a('<span class="label label-info"><span class="glyphicon glyphicon-comment"></span></span>', '#', [
                            'class' => 'showModalButton',
                            'value' => Url::to(['/data/save-logs', 'id' => $model->id, 'type' => 'sub']),
                            'title' => Yii::t('yii', 'Logs'),
                            'id' => 'commentLog-' . $model->id
                        ]);
                    },

                ],

            ],
        ],
    ]); ?>

</div>



<?= $this->registerJs('
    
    $("body").on("click", ".sub_change_status", function(e) {
     
        e.preventDefault(); 
        var data_id = $(this).attr("id"); 
        var status = $(this).val();
        
        $.ajax({
        
            url: "' . Yii::$app->request->baseUrl . '/data/update-status/",
            type: "POST",
            data: { status: status , id : data_id, type : "main"}, 
            success : function(res){
                
                console.log(res);
                
                var text = "UnApproved"; 
                
                if(res == "1"){ 
                     
                    swal({
                        title: "Success",
                        text: "Member " + text,
                        timer: 10000,
                        type: "success",
                        html: true,
                        showConfirmButton: true
                    });
                }     
                 
                $(this).attr("disabled",false);
            },
            error : function(data){
                console.log(data);
            }
        }); 
    });
    
    $("body").on("click", ".sub_change_status", function(e) {
     
        e.preventDefault(); 
        var data_id = $(this).attr("id"); 
        var status = $(this).val();
        
        $.ajax({
        
            url: "' . Yii::$app->request->baseUrl . '/data/update-status/",
            type: "POST",
            data: { status: status , id : data_id , type : "sub" }, 
            success : function(res){
                
                console.log(res);
                
                var text = "UnApproved"; 
                
                if(res == "1"){ 
                     
                    swal({
                        title: "Success",
                        text: "Member " + text,
                        timer: 10000,
                        type: "success",
                        html: true,
                        showConfirmButton: true
                    });
                }     
                 
                $(this).attr("disabled",false);
            },
            error : function(data){
                console.log(data);
            }
        }); 
    });
    
    
    $("body").on("click", ".sub_change_source", function(e) {
     
        e.preventDefault(); 
        var data_id = $(this).attr("id"); 
        var source = $(this).val();
        
        $.ajax({
        
            url: "' . Yii::$app->request->baseUrl . '/data/update-source-sub/",
            type: "POST",
            data: { source: source , id : data_id}, 
            success : function(res){
                
                if(res){
                    $("#success").removeClass("hidden");
                    $("#source_"+ data_id).text($(".change_source option:selected").text());
                }else{
                    $("#error").removeClass("hidden");
                }
               
               setTimeout(function(){ 
                    $(".change_source_label").addClass("hidden"); 
                    $("#modal").hide();
               }, 2000);
            },
            error : function(data){
                $("#error").removeClass("hidden");
                setTimeout(function(){ $(".change_source_label").addClass("hidden"); }, 2000);
            }
        }); 
    });
    
    
    $("body").on("click", "#SubmitForms", function(e) {
       
        var formAction = $("#LogsForm").attr("action");
        $.ajax({
           type: "POST",
           url: formAction,
           data: $("#LogsForm").serialize(),
           success: function (data) { 
               $("body").find("#comments_logs_container").html(data);
           },
           error: function () {
                alert("Error!!!");
           }
        });
        
        e.preventDefault();
    });
    
'); ?>